### ISSUE TITLE
Full page translation

### ISSUE THREAD

**Issue by guanzhangrtk** [deepext/feedback#2]
Any plans to support full page translations like the official Google Translate extension? Thanks!

**Comment by huan9huan** [comment]
Well, actually, because deepl api calling is pretty high(25$/Million Characters) document cost the quota&volume too much.
E.g. a document is about 10 KB, then user only view several articles to cost the FREE quota ( 15K characters).

**Comment by guanzhangrtk** [comment]
I see, thanks for the explanation!
