### ISSUE TITLE
Incorrect horizontal positioned deepext bar

### ISSUE THREAD

**Issue by ghost** [deepext/feedback#3]
On some Pages the translation bar does not cover the whole viewport width. Instead it starts at the calculated content offset.
In Short: the fixed positioned bar is missing a `left: 0;`

![blog fefe de_](https://user-images.githubusercontent.com/11646079/109837163-2fb65c00-7c45-11eb-9b2b-6a27be99042b.png)

**Comment by huan9huan** [comment]
Will cover this bug in next release

**Comment by huan9huan** [comment]
fixed in 1.6.0, please try!
