### ISSUE TITLE
New version bumps the close button (X) off-screen for some resolution.

### ISSUE THREAD

**Issue by Goldmes** [deepext/feedback#4]
## Expected Behavior
The close button still visible on a screen with resolution of 1366x768 (which shouldn't happen as it's still a very popular resolution).

## Actual Behavior
The close button isn't visible.

![image](https://user-images.githubusercontent.com/24835551/116554993-0dc81580-a926-11eb-827e-2edd1ac16ff0.png)

**Comment by huan9huan** [comment]
Resolved
